<a href="https://colab.research.google.com/github/Muskuu1109/ASSIGNMENT-ON-FUNCTION/blob/main/Feature_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. What is a parameter?

A parameter is a variable used in a model or algorithm that is set before the learning process begins. Parameters are typically adjusted during training to optimize model performance.


2. What is correlation?

Correlation is a statistical measure that describes the degree to which two variables are related to each other. It can be:
- Positive correlation: Both variables increase together.
- Negative correlation: One variable increases while the other decreases.
- Zero correlation: No relationship between the variables.





3. What does negative correlation mean?

Negative correlation means that as one variable increases, the other variable decreases. It indicates an inverse relationship between the two variables.
Example: The time spent watching TV and exercise levels often show negative correlation—more TV time means less physical activity.


4.Define Machine Learning. What are the main components in Machine Learning?

Machine Learning (ML) is a field of artificial intelligence that enables computers to learn patterns from data and make predictions or decisions.
The main components include:
- Data – The foundation of ML; includes raw information for training.
- Model – The mathematical representation used for learning patterns.
- Algorithms – Methods to train models (e.g., Decision Trees, Neural Networks).
- Evaluation Metrics – Measures of model performance (e.g., accuracy, precision).





5. How does loss value help in determining whether the model is good or not?

Loss value quantifies the difference between the model's predictions and actual values.
- A low loss value indicates good model performance.
- A high loss value suggests inaccurate predictions.

In optimization, models aim to minimize the loss function during training.


6. What are continuous and categorical variables?
- Continuous variables: Numerical data that can take any value within a range (e.g., height, temperature).
- Categorical variables: Data representing distinct groups or categories (e.g., gender, color).





7. How do we handle categorical variables in Machine Learning? What are the common techniques?

Categorical variables are transformed into numerical formats for ML models using techniques like:
- One-hot encoding – Creates binary columns for each category.
- Label encoding – Assigns numerical labels to categories.
- Binary encoding – Converts categorical data into binary representations.




In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

data = pd.DataFrame({'Color': ['Red', 'Blue', 'Green']})
encoder = OneHotEncoder()
encoded_data = encoder.fit_transform(data[['Color']]).toarray()
print(encoded_data)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


8. What do you mean by training and testing a dataset?
- Training dataset: Used to train a machine learning model.
- Testing dataset: Used to evaluate model accuracy and performance.




9. What is sklearn.preprocessing?

The sklearn.preprocessing module in Scikit-learn provides preprocessing tools such as:
- Scaling (StandardScaler, MinMaxScaler)
- Normalization
- Encoding categorical variables
- Feature extraction




In [2]:
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([[10], [20], [30]])
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)
print(scaled_data)

[[-1.22474487]
 [ 0.        ]
 [ 1.22474487]]


10. What is a Test set?

A test set is a portion of data reserved for evaluating a trained model’s performance. It helps determine how well the model generalizes to unseen data.


11. How do we split data for model fitting (training and testing) in Python?

In [3]:
from sklearn.model_selection import train_test_split

data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
train, test = train_test_split(data, test_size=0.2, random_state=42)

print(f'Train Set: {train}')
print(f'Test Set: {test}')

Train Set: [6, 1, 8, 3, 10, 5, 4, 7]
Test Set: [9, 2]


12. Why do we have to perform EDA before fitting a model to the data?

EDA (Exploratory Data Analysis) is crucial because it helps:
- Understand data distribution.
- Identify missing values and outliers.
- Determine feature relationships.
- Choose the best preprocessing and model approach.





13. How can you find correlation between variables in Python?



In [5]:
import pandas as pd
data = {'A': [1, 2, 3, 4, 5], 'B': [5, 4, 3, 2, 1]}
df = pd.DataFrame(data)
print(df.corr())  # Pearson correlation coefficient


     A    B
A  1.0 -1.0
B -1.0  1.0


14. What is causation? Explain difference between correlation and causation with an example.
- Correlation: Two variables move together but do not imply causation.
- Causation: One variable directly affects another.

15. What is an Optimizer? What are different types of optimizers?
An optimizer updates model weights to minimize loss during training.
Types:
- Gradient Descent: Moves in the direction of negative gradient.
- Stochastic Gradient Descent (SGD): Updates weights after each mini-batch.
- Adam: Uses momentum and adaptive learning rates.




In [7]:
import tensorflow as tf

optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)

16. What is sklearn.linear_model?
The sklearn.linear_model module provides linear models such as:
- Linear Regression
- Logistic Regression
- Ridge Regression



In [6]:
from sklearn.linear_model import LinearRegression
import numpy as np

X = np.array([[1], [2], [3], [4]])
y = np.array([2, 3, 5, 7])

model = LinearRegression()
model.fit(X, y)
print(model.predict([[5]]))

[8.5]


17. What is sklearn.tree?

The sklearn.tree module in Scikit-learn is used for Decision Trees, including:
- Classification Decision Trees (DecisionTreeClassifier)
- Regression Decision Trees (DecisionTreeRegressor)




In [8]:
from sklearn.tree import DecisionTreeClassifier

X = [[0], [1], [2], [3]]
y = [0, 1, 1, 0]

model = DecisionTreeClassifier()
model.fit(X, y)
print(model.predict([[2]]))

[1]


18. What is sklearn.svm?

In [9]:
from sklearn import svm

X = [[0, 0], [1, 1], [2, 2]]
y = [0, 1, 1]

model = svm.SVC(kernel='linear')
model.fit(X, y)
print(model.predict([[1, 1]]))

[1]


19. What is sklearn.cluster?

The sklearn.cluster module is used for clustering algorithms, including:
- K-Means clustering
- Agglomerative clustering
- DBSCAN




In [10]:
from sklearn.cluster import KMeans
import numpy as np

data = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
kmeans = KMeans(n_clusters=2)
kmeans.fit(data)
print(kmeans.labels_)

[1 1 0 0]


20. What is deep learning?

Deep Learning is a subset of Machine Learning that involves neural networks with multiple layers, enabling automatic feature extraction and representation learning.
Deep Learning is commonly used for:
- Image Recognition
- Natural Language Processing (NLP)
- Autonomous Systems




In [12]:
import tensorflow as tf

model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy')

21. What is a Neural Network?

A Neural Network is a computational system that mimics the functioning of the human brain, using interconnected layers of neurons to process data.
The basic types of Neural Networks:
- Artificial Neural Networks (ANN)
- Convolutional Neural Networks (CNN)
- Recurrent Neural Networks (RNN)




22. What is a loss function in Deep Learning?

A loss function quantifies how well a neural network's predictions match the actual target values. The model minimizes this loss during training.
Common loss functions:
- Mean Squared Error (MSE) – For regression tasks.
- Cross-Entropy Loss – For classification tasks.




In [14]:
import tensorflow as tf

loss_fn = tf.keras.losses.MeanSquaredError()
y_true = [3.0, 5.0, 7.0]
y_pred = [2.8, 5.2, 6.8]

print(loss_fn(y_true, y_pred).numpy())  # Calculates the loss

0.039999954
