<a href="https://colab.research.google.com/github/Muskuu1109/ASSIGNMENT-ON-FUNCTION/blob/main/NUMPY_ASSIGNMENT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Practical QUESTIONS***

**1.Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.**

In [3]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(array)

# Swap the first and second rows
array[[0, 1]] = array[[1, 0]]
print("\nArray after swapping rows:")
print(array)

# Swap the first and second columns
array[:, [0, 1]] = array[:, [1, 0]]
print("\nArray after swapping columns:")
print(array)


Original Array:
[[88 71 89]
 [89 13 59]
 [66 40 88]]

Array after swapping rows:
[[89 13 59]
 [88 71 89]
 [66 40 88]]

Array after swapping columns:
[[13 89 59]
 [71 88 89]
 [40 66 88]]


**2.Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.**

In [4]:
import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)
print("Original 1D Array:")
print(array_1d)

# Reshape the 1D array into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\nReshaped into 2x5 Array:")
print(array_2x5)

# Reshape the 1D array into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
print("\nReshaped into 5x2 Array:")
print(array_5x2)


Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped into 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped into 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


**3.Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.**

In [5]:
import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.random((4, 4))
print("Original 4x4 Array:")
print(array_4x4)

# Add a border of zeros around the 4x4 array
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with Zero Border:")
print(array_6x6)


Original 4x4 Array:
[[0.47997717 0.3927848  0.83607876 0.33739616]
 [0.64817187 0.36824154 0.95715516 0.14035078]
 [0.87008726 0.47360805 0.80091075 0.52047748]
 [0.67887953 0.72063265 0.58201979 0.53737323]]

6x6 Array with Zero Border:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.47997717 0.3927848  0.83607876 0.33739616 0.        ]
 [0.         0.64817187 0.36824154 0.95715516 0.14035078 0.        ]
 [0.         0.87008726 0.47360805 0.80091075 0.52047748 0.        ]
 [0.         0.67887953 0.72063265 0.58201979 0.53737323 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


**4.Using NumPy, create an array of integers from 10 to 60 with a step of 5.**

In [6]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)
print(array)


[10 15 20 25 30 35 40 45 50 55 60]


**5.Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.**

In [8]:
import numpy as np

# Create a NumPy array of strings
array = np.array(['pwskills', 'data', 'analaytics'])
print("Original Array:")
print(array)

# Apply uppercase transformation
uppercase_array = np.char.upper(array)
print("\nUppercase Array:")
print(uppercase_array)

# Apply lowercase transformation (although the original array is already in lowercase)
lowercase_array = np.char.lower(array)
print("\nLowercase Array:")
print(lowercase_array)

# Apply title case transformation
title_case_array = np.char.title(array)
print("\nTitle Case Array:")
print(title_case_array)

# Apply capitalize transformation
capitalize_array = np.char.capitalize(array)
print("\nCapitalize Array:")
print(capitalize_array)


Original Array:
['pwskills' 'data' 'analaytics']

Uppercase Array:
['PWSKILLS' 'DATA' 'ANALAYTICS']

Lowercase Array:
['pwskills' 'data' 'analaytics']

Title Case Array:
['Pwskills' 'Data' 'Analaytics']

Capitalize Array:
['Pwskills' 'Data' 'Analaytics']


**6. Generate a NumPy array of words. Insert a space between each character of every word in the array.**

In [9]:
import numpy as np

# Create a NumPy array of words
words_array = np.array(['course', 'numpy', 'assignment'])
print("Original Array:")
print(words_array)

# Insert a space between each character of every word
spaced_words_array = np.char.join(' ', words_array)
print("\nArray with Spaces Between Characters:")
print(spaced_words_array)


Original Array:
['course' 'numpy' 'assignment']

Array with Spaces Between Characters:
['c o u r s e' 'n u m p y' 'a s s i g n m e n t']


**7.Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.**

In [14]:
import numpy as np

array1 = np.array([[3, 2, 7], [4, 8, 9]])
array2 = np.array([[4,5,1], [2,5,6]])

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)

# Element-wise addition
addition = np.add(array1, array2)
print("\nElement-wise Addition:")
print(addition)

# Element-wise subtraction
subtraction = np.subtract(array1, array2)
print("\nElement-wise Subtraction:")
print(subtraction)

# Element-wise multiplication
multiplication = np.multiply(array1, array2)
print("\nElement-wise Multiplication:")
print(multiplication)

# Element-wise division
division = np.divide(array1, array2)
print("\nElement-wise Division:")
print(division)





Array 1:
[[3 2 7]
 [4 8 9]]

Array 2:
[[4 5 1]
 [2 5 6]]

Element-wise Addition:
[[ 7  7  8]
 [ 6 13 15]]

Element-wise Subtraction:
[[-1 -3  6]
 [ 2  3  3]]

Element-wise Multiplication:
[[12 10  7]
 [ 8 40 54]]

Element-wise Division:
[[0.75 0.4  7.  ]
 [2.   1.6  1.5 ]]


**8.Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.**

In [15]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


**9.Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.**

In [16]:
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1000, size=100)
print("Random Array:")
print(random_array)

def is_prime(n):
    """Check if a number is a prime number."""
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

# Find all prime numbers in the array
primes = np.array([x for x in random_array if is_prime(x)])
print("\nPrime Numbers in Array:")
print(primes)


Random Array:
[544 543 714 244 151 675 510 459 882 183  28 802 128 128 932  53 901 550
 488 756 273 335 388 617  42 442 543 888 257 321 999 937  57 291 870 119
 779 430  82  91 896 398 611 565 908 633 938  84 203 324 774 964  47 639
 131 972 868 180 846 143 660 227 954 791 719 909 373 853 560 305 581 169
 675 448  95 197 606 256 881 690 292 930 816 861 387 610 554 973 368 999
 917 201 383 512 906 370 555 954 383  23]

Prime Numbers in Array:
[151  53 617 257 937  47 131 227 719 373 853 197 881 383 383  23]


**10.Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.**

In [19]:
import numpy as np

#Generate daily temperatures for a month (30 days)
np.random.seed(0)  # For reproducibility
daily_temperatures = np.random.uniform(low=0, high=35, size=30)  # Temperatures between 0 and 35 degrees
print("Daily Temperatures for the Month:")
print(daily_temperatures)

#Reshape the array to represent weeks (assuming 30 days = 4 weeks + 2 extra days)
#Reshape to 5 weeks of 6 days
reshaped_temperatures = daily_temperatures.reshape(5, 6) #Change the dimensions of the reshaped array to 5x6
print("\nReshaped Temperatures (5 weeks x 6 days):")
print(reshaped_temperatures)

#Calculate weekly averages
weekly_averages = np.mean(reshaped_temperatures, axis=1)
print("\nWeekly Averages:")
print(weekly_averages)


Daily Temperatures for the Month:
[19.20847264 25.03162782 21.09671816 19.0709114  14.82791798 22.60629396
 15.31555239 31.21205503 33.72819662 13.42045316 27.71037633 18.51132219
 19.88155964 32.39588234  2.48626204  3.04952549  0.70764391 29.14169459
 27.23548628 30.45042519 34.25164198 27.97054975 16.15177768 27.31852117
  4.13960491 22.39723575  5.01736506 33.0634121  18.26469126 14.5131679 ]

Reshaped Temperatures (5 weeks x 6 days):
[[19.20847264 25.03162782 21.09671816 19.0709114  14.82791798 22.60629396]
 [15.31555239 31.21205503 33.72819662 13.42045316 27.71037633 18.51132219]
 [19.88155964 32.39588234  2.48626204  3.04952549  0.70764391 29.14169459]
 [27.23548628 30.45042519 34.25164198 27.97054975 16.15177768 27.31852117]
 [ 4.13960491 22.39723575  5.01736506 33.0634121  18.26469126 14.5131679 ]]

Weekly Averages:
[20.30699033 23.31632595 14.610428   27.22973367 16.23257949]
